Feature/development
boldlink/terraform-aws-sns pull request #5
Opened 2022-04-26 11:57 UTC by patrickmukumbu

Changed source to point to tf registry

2022-04-28 18:39 UTC, mariomerco requested changes
The following variable names are repeated in the file `variables.tf`:
```
- use_default_kms_key
- create_kms_key
```

2022-04-29 09:53 UTC, hugoalmeida264 approved these changes

2022-05-02 14:30 UTC, mariomerco commented
Looking good after addressing the comment!

2022-05-02 14:30 UTC, mariomerco approved these changes

2022-05-09 07:14 UTC, merged